services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    command: npm run dev

  chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium_chrome
    shm_size: "2g"
    restart: unless-stopped
    ports:
      - "4444:4444"
      - "7900:7900"

  scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_scheduler
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    command: /var/www/html/scheduler.sh
    depends_on:
      - backend
      - chrome

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8010:8000"
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      - DB_CONNECTION=mongodb
      - DB_PORT=27017
      - MONGODB_URI=mongodb+srv://stefanusricotif22:bobgaming@simpeldb.zjrwtun.mongodb.net/
      - MONGODB_DATABASE=spmev2
      - PHP_CLI_SERVER_WORKERS=4
      - CHOKIDAR_USEPOLLING=true
    command: php artisan serve --host=0.0.0.0 --port=8000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "9010:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/public:/usr/share/nginx/html
      - ./backend/storage:/var/www/html/storage
    depends_on:
      - frontend
      - backend

networks:
  kota107-prod:
    driver: bridge
