FROM stefanusrico/siaps_be:latest

# Ensure storage directory exists
RUN mkdir -p /var/www/html/storage/app /var/www/html/storage/logs \
    /var/www/html/storage/framework/cache \
    /var/www/html/storage/framework/sessions \
    /var/www/html/storage/framework/views

# Copy your local storage directory to the image
COPY ./storage/ /var/www/html/storage/

# Fix permissions
RUN chown -R www-data:www-data /var/www/html/storage \
    && chmod -R 755 /var/www/html/storage